// Central configuration for the Syrup signal flow presentation.
export const HIGHLIGHT_DURATION_MS = 5000;

export const presets = {
  audioPath: { label: "Highlight Audio Path", nodes: null }, // BFS-driven
  chainA: {
    label: "A/B: Chain A",
    nodes: [
      "AUDIO INPUT",
      "SIGNAL MANAGER",
      "Signal Input",
      "Signal Bridge",
      "EFFECTS SIGNAL MANAGER",
      "Effects Signal Manager Input",
      "Master Control",
      "MODULE MANAGER",
      "Compression",
      "Limiter",
      "Gate",
      "CHANNEL EFFECTS MANAGER",
      "Channel Signal Bridge",
      "Reverb",
      "Delay",
      "Signal Bridge Output",
      "Output Main",
      "AUDIO OUTPUT",
    ],
  },
  chainB: {
    label: "A/B: Chain B",
    nodes: [
      "AUDIO INPUT",
      "SIGNAL MANAGER",
      "Signal Input",
      "Signal Bridge",
      "EFFECTS SIGNAL MANAGER",
      "Effects Signal Manager Input",
      "Master Control",
      "MODULE MANAGER",
      "Compression",
      "Limiter",
      "Gate",
      "CHANNEL EFFECTS MANAGER",
      "Channel Signal Bridge",
      "Saturation",
      "Pitch Shifter",
      "Signal Bridge Output",
      "Output Main",
      "AUDIO OUTPUT",
    ],
  },
  fxChainA: {
    label: "FX Chain A",
    nodes: [
      "AUDIO INPUT",
      "SIGNAL MANAGER",
      "Signal Input",
      "Signal Bridge",
      "EFFECTS SIGNAL MANAGER",
      "Effects Signal Manager Input",
      "Master Control",
      "MODULE MANAGER",
      "Compression",
      "Limiter",
      "Gate",
      "CHANNEL EFFECTS MANAGER",
      "Channel Signal Bridge",
      "Reverb",
      "Delay",
      "Saturation",
      "Pitch Shifter",
      "Channel Signal Bridge",
      "Signal Bridge Output",
      "Output Main",
      "AUDIO OUTPUT",
    ],
  },
  dryPath: {
    label: "Dry Path",
    nodes: [
      "AUDIO INPUT",
      "SIGNAL MANAGER",
      "Signal Input",
      "Signal Bridge",
      "Signal Bridge Output",
      "Signal Output",
      "Output Main",
      "AUDIO OUTPUT",
    ],
  },
};

export const collapsibleGroups = {
  Reverb: [
    "Reverb Input",
    "Reverb Output",
    "Reverb Parameter Control",
    "Reverb Processing",
    "Reverb Wet/Dry Mix",
  ],
  Delay: [
    "Delay Input",
    "Delay Output",
    "Delay Parameter Control",
    "Delay Processing",
    "Delay Wet/Dry Mix",
  ],
  Saturation: [
    "Saturation Input",
    "Saturation Output",
    "Saturation Parameter Control",
    "Saturation Processing",
    "Saturation Wet/Dry Mix",
  ],
  "Pitch Shifter": [
    "Pitch Shifter Input",
    "Pitch Shifter Output",
    "Pitch Shifter Parameter Control",
    "Pitch Shifter Processing",
    "Pitch Shifter Wet/Dry Mix",
  ],
  "Master Control": [
    "Master Control Input",
    "Master Control Output",
    "Master Control Parameter Control",
    "Master Control Processing",
    "Master Control Wet/Dry Mix",
  ],
};

export const modes = {
  architect: {
    label: "Architect",
    visible: null, // null = show all
  },
  endUser: {
    label: "End-user",
    visible: new Set([
      "AUDIO INPUT",
      "SIGNAL MANAGER",
      "Signal Bridge",
      "EFFECTS SIGNAL MANAGER",
      "Master Control",
      "MODULE MANAGER",
      "Compression",
      "Limiter",
      "Gate",
      "CHANNEL EFFECTS MANAGER",
      "Channel Signal Bridge",
      "Reverb",
      "Delay",
      "Saturation",
      "Pitch Shifter",
      "Signal Bridge Output",
      "Output Main",
      "AUDIO OUTPUT",
    ]),
  },
};

export const legendIcons = {
  audio: "🔊",
  io: "🎛️",
  plugin__io: "🎛️",
  manager: "🧭",
  host: "🛰️",
  process: "🧪",
  control: "🎚️",
};
